- name: Demo on facts 
  hosts: all 
  gather_facts: False
  tasks:
    - name: Printing a fact variabe
      debug:
        msg: "{{ansible_distribution}}"
    - name: Printing the mac id of the remote machine 
      debug:
        msg: "{{ansible_default_ipv4.macaddress}}"
 