- name: Installing WebServer
  package:
    name: httpd 

- name: Copying the proxy file 
  copy:  
    src: proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf 
  notify: Restart HTTPD 

- name: Download default index file  
  get_url:
    url: "{{INDEX_URL}}"
    dest: /var/www/html/index.html
  notify: Restart HTTPD  

- name: Start Httpd 
  service:
    name: httpd
    state: started 
    enabled: yes